services:
  db:
    image: postgres:15
    container_name: postgres-barbearia
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: barbearia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: api-barbearia
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/barbearia_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata: