spring.application.name=agenda

spring.jpa.properties.hibernate.format_sql=true

# Avisa ao Spring para ler o arquivo messages.properties
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Se existir a variável SPRING_DATASOURCE_URL, use ela.
# Se não existir, use o localhost (padrão do IntelliJ).
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/barbearia_db}
//spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
//spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

//spring.jpa.hibernate.ddl-auto=update
//spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123



spring.datasource.url=jdbc:postgresql://db:5432/barbearia_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Isso ajuda a evitar o erro 500 se o Swagger estiver confuso
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
api.security.token.secret=minha_chave_secreta_muito_longa_com_muitos_caracteres_123